// GENERATED by tools/gen_aa_assets.py - do not edit.
// Anti-aliased glyph and icon coverage masks (4 bit) for the v2 UI.
// Type: Inter Display (c) The Inter Project Authors, SIL OFL 1.1.
#pragma once
#include "aa_gfx.h"

namespace aa_assets {

extern const aa::Font kFontTime;   // Inter Display Regular 76 px
extern const aa::Font kFontCode;   // Inter Display SemiBold 40 px
extern const aa::Font kFontTitle;   // Inter Display SemiBold 20 px
extern const aa::Font kFontUi;   // Inter Display SemiBold 15 px
extern const aa::Font kFontSmall;   // Inter Display Medium 13 px
extern const aa::Font kFontLabel;   // Inter Display SemiBold 12 px
extern const aa::Font kFontMsg;   // Inter Display Medium 19 px

enum MaskId : uint8_t {
  M_SUN_16 = 0,
  M_PARTLY_16 = 1,
  M_CLOUD_16 = 2,
  M_RAIN_16 = 3,
  M_STORM_16 = 4,
  M_SNOW_16 = 5,
  M_FOG_16 = 6,
  M_MOON_16 = 7,
  M_CALENDAR_16 = 8,
  M_BELL_16 = 9,
  M_HEART_16 = 10,
  M_STAR_16 = 11,
  M_CHAT_16 = 12,
  M_CHECK_16 = 13,
  M_ALERT_16 = 14,
  M_SUN_34 = 15,
  M_PARTLY_34 = 16,
  M_CLOUD_34 = 17,
  M_RAIN_34 = 18,
  M_STORM_34 = 19,
  M_SNOW_34 = 20,
  M_FOG_34 = 21,
  M_MOON_34 = 22,
  M_CALENDAR_34 = 23,
  M_BELL_34 = 24,
  M_HEART_34 = 25,
  M_STAR_34 = 26,
  M_CHAT_34 = 27,
  M_CHECK_34 = 28,
  M_ALERT_34 = 29,
  M_BT_16 = 30,
  M_BT_44 = 31,
  M_WIFI0_22 = 32,
  M_WIFI1_22 = 33,
  M_WIFI2_22 = 34,
  M_WIFI3_22 = 35,
  M_POWER_20 = 36,
  M_LOCK_36 = 37,
  M_BACK_18 = 38,
  M_CHECK_40 = 39,
  M_EYEOFF_36 = 40,
  M_COUNT = 41
};
extern const aa::Mask kMasks[M_COUNT];

}  // namespace aa_assets
