#!/usr/bin/env python3
"""Bake Friend Radar's anti-aliased UI fonts into C++ source.

Rasterises Aileron Regular (by Sora Sagano, dotcolon.net, CC0 1.0 public
domain dedication; the copy bundled with Pillow >= 10.1 is used) at a few
pixel sizes into 4-bit alpha glyph bitmaps, and writes
src/apps/radar/gfx/fr_font_data.cpp. Semi-bold variants are made by
rendering at 4x with a thin stroke and box-filtering down.

    python3 tools/bake_fonts.py            # regenerate the C++ file
    python3 tools/bake_fonts.py --preview out.png   # also write a specimen

Character set: printable ASCII plus three extras mapped to single bytes so
C strings can use them: 0x7F middle dot, 0x80 ellipsis, 0x81 degree sign.
(Pillow's trimmed Aileron has no bullet or arrows; the UI draws those.)
"""
import argparse
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/apps/radar/gfx/fr_font_data.cpp"

EXTRAS = {0x7F: "·", 0x80: "…", 0x81: "°"}
FIRST, LAST = 0x20, 0x81

# name, pixel size, semi-bold
FONTS = [
    ("kFontXS", 12, False),
    ("kFontS", 14, False),
    ("kFontM", 17, False),
    ("kFontMB", 17, True),
    ("kFontL", 22, True),
    ("kFontXL", 32, True),
    ("kFontD", 44, False),
]
SS = 4  # supersampling factor for bold synthesis


def char_for(code):
    return EXTRAS.get(code, chr(code))


def render_glyph(font_big, font_1x, ch, bold):
    """Return (alpha rows [h][w] 0..255, dx, dy, advance) at 1x."""
    if not bold:
        bbox = font_1x.getbbox(ch)
        adv = int(round(font_1x.getlength(ch)))
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            return [], 0, 0, adv
        x0, y0, x1, y1 = bbox
        img = Image.new("L", (x1 - x0, y1 - y0), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font_1x, fill=255)
        rows = [[img.getpixel((x, y)) for x in range(img.width)] for y in range(img.height)]
        asc = font_1x.getmetrics()[0]
        return rows, x0, y0 - asc, adv
    # Semi-bold: 4x render with stroke, then box filter.
    stroke = 2
    bbox = font_big.getbbox(ch, stroke_width=stroke)
    adv = int(round(font_big.getlength(ch) / SS + 0.5))
    if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
        return [], 0, 0, adv
    x0, y0, x1, y1 = bbox
    # align the big bbox to the SS grid so downsampling is phase-correct
    ax0, ay0 = (x0 // SS) * SS, (y0 // SS) * SS
    ax1, ay1 = -(-x1 // SS) * SS, -(-y1 // SS) * SS
    img = Image.new("L", (ax1 - ax0, ay1 - ay0), 0)
    ImageDraw.Draw(img).text((-ax0, -ay0), ch, font=font_big, fill=255,
                             stroke_width=stroke, stroke_fill=255)
    small = img.resize((img.width // SS, img.height // SS), Image.BOX)
    rows = [[small.getpixel((x, y)) for x in range(small.width)] for y in range(small.height)]
    asc = font_big.getmetrics()[0] / SS
    return rows, ax0 // SS, int(round(ay0 / SS - asc)), adv


def trim(rows, dx, dy):
    """Drop fully transparent border rows/columns."""
    if not rows:
        return rows, dx, dy
    while rows and max(rows[0]) < 8:
        rows = rows[1:]; dy += 1
    while rows and max(rows[-1]) < 8:
        rows = rows[:-1]
    if not rows:
        return rows, dx, dy
    while rows[0] and max(r[0] for r in rows) < 8:
        rows = [r[1:] for r in rows]; dx += 1
    while rows[0] and max(r[-1] for r in rows) < 8:
        rows = [r[:-1] for r in rows]
    return rows, dx, dy


def bake(name, size, bold):
    font_1x = ImageFont.load_default(size=size)
    font_big = ImageFont.load_default(size=size * SS)
    asc, desc = font_1x.getmetrics()
    cap = font_1x.getbbox("H")
    cap_h = cap[3] - cap[1]
    glyphs, bits = [], []
    for code in range(FIRST, LAST + 1):
        rows, dx, dy, adv = render_glyph(font_big, font_1x, char_for(code), bold)
        rows, dx, dy = trim(rows, dx, dy)
        if code == 0x20:
            rows = []
        h = len(rows)
        w = len(rows[0]) if h else 0
        off = len(bits)
        nibbles = [min(15, (v + 8) // 17) for r in rows for v in r]
        if len(nibbles) % 2:
            nibbles.append(0)
        for i in range(0, len(nibbles), 2):
            bits.append((nibbles[i] << 4) | nibbles[i + 1])
        glyphs.append((off, w, h, dx, dy, adv, code))
    line_h = asc + desc + (2 if size < 20 else 3)
    return dict(name=name, size=size, bold=bold, glyphs=glyphs, bits=bits,
                line_h=line_h, ascent=asc, cap_h=cap_h)


def emit(fonts):
    out = []
    out.append("// GENERATED by tools/bake_fonts.py -- do not edit by hand.")
    out.append("// Aileron Regular by Sora Sagano (dotcolon.net), CC0 1.0 public domain")
    out.append("// dedication, rasterised to 4-bit alpha. Semi-bold variants are synthesised.")
    out.append('#include "fr_font.h"')
    out.append("")
    out.append("namespace fr {")
    total = 0
    for f in fonts:
        n = f["name"]
        out.append("")
        out.append(f"// {n}: {f['size']} px{' semi-bold' if f['bold'] else ''}, "
                   f"line {f['line_h']} px, cap height {f['cap_h']} px")
        out.append(f"static const uint8_t {n}Bits[] = {{")
        b = f["bits"]
        for i in range(0, len(b), 20):
            out.append("  " + ",".join(f"0x{v:02X}" for v in b[i:i + 20]) + ",")
        out.append("};")
        out.append(f"static const FontGlyph {n}Glyphs[] = {{")
        for (off, w, h, dx, dy, adv, code) in f["glyphs"]:
            label = repr(char_for(code)).replace("\\", "/")
            out.append(f"  {{{off:5d}, {w:2d}, {h:2d}, {dx:3d}, {dy:4d}, {adv:2d}}},  // 0x{code:02X} {label}")
        out.append("};")
        out.append(f"const Font {n} = {{ {n}Bits, {n}Glyphs, 0x{FIRST:02X}, 0x{LAST:02X}, "
                   f"{f['line_h']}, {f['ascent']}, {f['cap_h']} }};")
        total += len(b) + 7 * len(f["glyphs"])
    out.append("")
    out.append("}  // namespace fr")
    out.append(f"// total font data: ~{total} bytes")
    return "\n".join(out) + "\n"


def preview(fonts, path):
    """Render a specimen with the same 4-bit data the firmware uses."""
    W, H = 480, 420
    img = Image.new("RGB", (W, H), (7, 11, 20))
    y = 8
    texts = {"kFontXS": "NEAR  AROUND  FAR  VISIBLE AS KYLE  ON AIR",
             "kFontD": "-61 dBm  2 m",
             "kFontS": "Visible as Kyle \x7f 3 nearby \x7f 21\x81 Ewan 2 m",
             "kFontM": "Right here \x7f Near \x7f Around \x7f Far\x80",
             "kFontMB": "Add mate \x7f Rename \x7f Calibrate 1 m",
             "kFontL": "Ewan is near!  -62 dBm",
             "kFontXL": "High five! 0123"}
    for f in fonts:
        y += f["ascent"] + 4
        x = 8
        for ch in texts[f["name"]]:
            code = ord(ch)
            g = f["glyphs"][code - FIRST]
            off, w, h, dx, dy, adv, _ = g
            for j in range(h):
                for i in range(w):
                    k = j * w + i
                    byte = f["bits"][off + k // 2]
                    a = (byte >> 4) if k % 2 == 0 else (byte & 15)
                    if a:
                        px, py = x + dx + i, y + dy + j
                        if 0 <= px < W and 0 <= py < H:
                            bg = img.getpixel((px, py))
                            fg = (232, 241, 244)
                            t = a / 15
                            img.putpixel((px, py), tuple(int(bg[c] * (1 - t) + fg[c] * t) for c in range(3)))
            x += adv
        y += f["line_h"] - f["ascent"] + 4
    img = img.resize((W * 2, H * 2), Image.NEAREST)
    img.save(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", type=Path)
    args = ap.parse_args()
    fonts = [bake(*spec) for spec in FONTS]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit(fonts))
    print(f"wrote {OUT.relative_to(ROOT)}")
    for f in fonts:
        print(f"  {f['name']}: {len(f['bits'])} bytes of bitmap, line {f['line_h']}, ascent {f['ascent']}")
    if args.preview:
        preview(fonts, args.preview)
        print(f"preview -> {args.preview}")


if __name__ == "__main__":
    sys.exit(main())
