// Anti-aliased bitmap fonts for Friend Radar (4-bit alpha glyphs).
// Data is generated by tools/bake_fonts.py into fr_font_data.cpp.
#pragma once
#include <stdint.h>

namespace fr {

struct FontGlyph {
  uint16_t off;    // byte offset of the packed 4-bit bitmap
  uint8_t  w, h;   // bitmap size
  int8_t   dx;     // pen x -> bitmap left
  int8_t   dy;     // baseline -> bitmap top (negative = above the baseline)
  uint8_t  adv;    // pen advance
};

struct Font {
  const uint8_t   *bits;
  const FontGlyph *glyphs;
  uint8_t first, last;
  uint8_t lineH;    // recommended line advance
  uint8_t ascent;   // baseline offset from the top of a line box
  uint8_t capH;     // height of a capital letter
};

// Extra single-byte characters available in every font.
#define FR_MIDDOT   "\x7f"
#define FR_ELLIPSIS "\x80"
#define FR_DEGREE   "\x81"

extern const Font kFontXS;   // 12 px regular  - engraved small caps
extern const Font kFontS;    // 14 px regular  - labels, secondary text
extern const Font kFontM;    // 17 px regular  - body text, list rows
extern const Font kFontMB;   // 17 px semi-bold - buttons, emphasis
extern const Font kFontL;    // 22 px semi-bold - titles, names
extern const Font kFontXL;   // 32 px semi-bold - headlines
extern const Font kFontD;    // 44 px regular  - display numerals / distances

}  // namespace fr
